networks: 
  mynetwork:
    name: mynetwork
    attachable: true

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: clear
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - 3306:3306
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
      
  keycloak:
    image: keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    networks:
      - mynetwork
    depends_on:
      - mysql
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 3333:3333
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-http.conf:/etc/nginx/conf.d/nginx-http.conf
  
  ether:
    image: ether
    container_name: ether
    ports:
      - 9000:9000
    networks:
      - mynetwork
  

volumes:
  mysql_data: