FROM quay.io/keycloak/keycloak

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_DB=mysql
ENV KC_DB_URL=jdbc:mysql://mysql/keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=keycloak

EXPOSE 8080

CMD [ "start-dev --http-relative-path=/auth --proxy=edge"]